let prompts = [
    "If you could raise yourself, what would you do differently from the people who raised you?",
    "What's your favorite lyric(s) from your favorite song? And why does it connect with you so much?",
    "What is one thing you did really well today?",
    "Describe a place that exists only in your imagination.",
    "Write a letter to your younger self. What advice would you give?",
    "Write a letter to your future self. What advice would you give?",
    "If you were transported into the world/setting of your favorite tv show/book/movie/game/etc, what would happen to you?",
    "What does your ideal day look like?",
    "Make a list of 8 things you are grateful for. Describe how each one makes you feel.",
    "If you could see them again, what would you say? Would you say anything?",
    "Pick a photograph from your phone or album. Describe the story behind it. Or make up one!",
    "What is something that has been bothering you for a while, but you haven't been able to talk about it?",
    "What is a recent mistake or failure you experienced? How did it make you feel?",
    "Write about a time you truly felt loved and cared for and how that has changed you. If you haven't experienced it yet, write about what that would look like for you.",
    "What is something you're scared to try, but would love to have the courage to?",
    "Write about your favorite place. Why is it important to you? What memories do you associate with that place? Is there anyone you would like to bring back there?",
    "What emotions are you feeling right now?",
    "What's something new you want to accomplish this month?",
    "What's something that disappointed you today?",
    "What are three things you can do today to take of yourself?",
    "What are your deal-breakers when it comes to relationships, both platonic and romantic?",
    "What are your thoughts on getting older? Are you scared or eager to age?",
    "Name at least one person whose life you impacted in a positive way.",
    "What did you eat as a child that you can't stand now as an adult?",
    "Is it important to always be genuine?",
    "How did you meet your first love?",
    "When was the last time you lied?",
    "Write about the last time the weather scared you.",
    "If the world ends tomorrow, what is the first thing you want to do?",
    "Who do you trust the most and why?",
    "What do you eat now that you couldn't stand when you were a child?",
    "What is something you want for your birthday?",
    "Where do you hope life will take you in the next 10 years?",
    "You have thirty minutes to come up with the most interesting tv show you can to pitch to a network.",
    "Do you remember any of your friends from kindergarten? If yes, what do you remember about them?",
    "What was your first pet's name?",
    "Write the title of your autobiography and explain why you chose it.",
    "Describe what falling in love feels like to you.",
    "What is your favorite hobby? And where is your favorite place to do it?",
    "Explain how you chose your career path. Are you satisfied with your choice?",
    "What do you think about the ocean? Does it scare or fascinate you?",
    "What is the scariest nightmare you've ever had?",
    "What would you change about your personality if you could?",
    "If you suddenly became a world leader, what is the first thing you'd do?",
    "Name a trivial thing that annoys you that most people would be confused by if they heard you complaining about it?",
    "Have you ever had a near death experience? What happened?",
    "Describe in detail your favorite sound.",
    "Who was the best teacher you've ever had? If you could meet them again, what would you tell them?",
    "Which situations do you tend to resolve by flipping a coin or leaving it up to chance?",
    "What do the holidays mean to you?",
    "Do you currently have any savings? What are you saving up for?",
    "Which animal do you most resemble?",
    "If you could be fluent in any language, which would you choose and why?",
    "If you had an unlimited budget to furnish your home, what would you change?",
    "If you were in a band, what position would you take? Vocals? Drums? Keyboard? Bass?",
    "What is your most prized posession?",
    "What do you live for?",
    "Write about yourself from the perspective of a stranger. What's the first thing they'd notice about you?",
    "If you suddenly gained superpowers, would you tell anyone? If yes, who?",
    "What's the plot of your comfort movie/book/tv show/game in one sentence?",
    "Where were you born? What do you remember about that place?",
    "Describe the ocean to someone who's never been.",
    "Describe snow to someone who has never seen it.",
    "If you have a favorite painting, describe it to someone who's never seen it before.",
    "If you found a suitcase full of money on the sidewalk, what would you do?",
    "What are some of your irrational fears? When did you get them?",
    "What is the best gift you've ever received and why?",
    "If you could donate years of your life to someone else, who would you give them to?",
    "If you switched bodies with the last person you made eye contact with, what would you do?",
    "Are there any recurring themes in your dreams/nightmares? What are they?",
    "Why do you journal?",
    "Describe yourself using only two words. One positive and one negative.",
    "What does the word 'love' mean to you? How would you define it?",
    "If you were a color, what color would you be?",
    "Fill in the blank: If I _________ before I die, I can die happy.",
    "Fill in the blank: I know I have to ______, but I really don't want to.",
    "Write down one sentence full of praise for yourself. No critiques.",
    "What is your least favorite chore and why?",
    "Who do you trust the least and why?",
    "Would you rather live forever or know the date of your death ahead of time?",
    "What is a modern day convenience you couldn't do without?",
    "When you were a kid, did you ever swallow something that wasn't food?",
    "What's your favorite thing to order at restaurants?",
    "What is the first video game you ever finished?",
    "Have you ever won first place?",
    "Have you ever questioned your family's morals/values?",
    "What is the best party you have ever been to?",
    "What is the strangest thing you ever witnessed on public transport?",
    "If money wasn't an issue, what dream item would you splurge on?",
    "What was life like when you were a kid?",
    "What's the strangest food you've ever eaten?",
    "What do you have in common with your parents? And if you weren't related, would you be friends?",
    "Who is the most famous person from your city?",
    "What words would you love to hear most from your loved ones right now?",
    "Is there a scent that reminds you of home?",
    "If you could ask your parents absolutely anything, what would you ask?",
    "Who is the most interesting person you've ever met?",
    "What do you think the world will look like in 50 years?",
    "What is your favorite time of day?",
    "If you could change your name, would you? Why or why not?",
    "If you could live anywhere in the world, where would you live?",
    "On average, do you live for today or tomorrow?",
    "What has been the proudest moment of your life so far?",
    "What is your main goal for next year?",
    "Write about a time you helped someone without expecting anything in return.",
    "What's your favorite room in your house?",
    "What's the worst thing someone could do on a first date with you?",
    "What kind of thoughts run through your mind before you fall asleep? Do you think about your day or the next day?",
    "What personality trait do you admire most in other people?",
    "What words or phrases do you use often in your daily life?",
    "If you could choose what you'd reincarnate as, what would you choose?",
    "What is something you're really looking forward to?",
    "What is something you're not looking forward to?",
    "What is your favorite month and why?",
    "If you could only take one person on a trip around the world, who would you take and why?",
    "If you were a fly landing on a wall in your home, what would you see happening?",
    "Some people like to have a cup of coffee every morning. Do you have any daily/weekly rituals like that?",
    "What are some nutritious foods you actually like?",
    "What is most important to you in a friend; loyalty, generosity or honesty?",
    "What is one thing that will always make you laugh?",
    "Do you have a favorite cartoon from childhood?",
    "Do you feel comfortable when you sleep at someone else's house?",
    "Would you change anything about your appearance?",
    "Do you have the most fun alone, with a large group, or with just a few friends?",
    "Fill in the blank: I wish I had another chance to _______.",
    "Fill in the blank. I need to forgive myself for ________.",
    "What's the strangest outfit you've ever worn?",
    "When was the last time you cried and why?",
    "Is it better to always be honest? Why or why not?",
    "Is there anyone you wish you could see more often than you do now?",
    "Name one item that can always be found in your refrigerator.",
    "If you could have your own podcast, what would it be about?",
    "What fears or insecurities are holding you back right now?",
    "Do you like being alone? Why or why not?",
    "Do your responsibilities leave you enough time for yourself? Are you able to relax?",
    "What did you once hate/dislike, but now like?",
    "Would you prefer feedback that's encouraging and understanding, or tough but honest?",
    "Are you trying too hard to be happy?",
    "How good are you at waiting for what you really want?",
    "Which do you enjoy more: collaboration or competition?",
    "What's the worst prank someone's ever played on you?",
    "Do you apologize too much or not enough?",
    "What pushes you to keep going?",
    "Have you ever successfully changed someone's mind?",
    "Do you have any hobbies that you've never shared with others? Why keep it to yourself?",
    "What advice would you give to younger kids about middle or high school?",
    "What do older generations tend to misunderstand about you?",
    "When's the last time you eavesdropped?",
    "What life lessons can you learn from other religions?",
    "What does money mean to you?",
    "Does your persona on social media match your personality in real life?",
    "What are you listening to? What do you like about it?",
    "What are your earliest memories of music?",
    "Make a best of the year list for your favorite music, movies, books, or games and write what you liked and disliked about each one.",
    "Do you like your handwriting? Has it improved or worsened over the years?",
    "What 'mundane moment' from your life could be turned into a great song/movie/book/etc?",
    "What is your favorite thing you've ever written?",
    "How quick are you at coming up with witty comebacks?",
    "Do you prefer to talk over the phone or simply text? Why one or the other?",
    "What's the last word you learned in a language other than the one you speak natively?",
    "What do you hope to get out of life?",
    "What do you wish other people knew about you?",
    "How did you start doing something you love?",
    "What have you made yourself?",
    "Would you quit a job if your values did not match your employer's?",
    "Have you ever felt left out by the people around you? What did you do?",
    "How would you feel if two people who only met because of you, suddenly became close to each other and distant with you?",
    "Do you find it easier to connect with others online or in person?",
    "What advice would you give to someone who just started dating?",
    "What's your method for getting over a break-up?",
    "What do you like to do to stay active? Is it more of a chore than something you actually enjoy?",
    "What is your favorite clothing item you own?",
    "Did you get enough sleep last night?",
    "If you've ever revisited a place from your childhood, did it feel the same as you remembered?",
    "What would you most like to learn to cook or bake?",
    "What dish do you think you're qualified to judge in a cook-off?",
    "Do you like to celebrate your birthday? How do you celebrate?",
    "Do you find that your mood shifts with the weather? When is it really noticeable?",
    "How do you feel about zoos?",
    "Do you trust your government?",
    "What national or international event(s) did you live through and what can you recall about it?",
    "If you were a billionaire philanthropist, what cause(s) would you support?",
    "What would you like to be doing when you're 75?",
    "What small detail from your life would you want your obituary to mention?",
    "How resilient are you?",
    "Is it hard for you to believe people when they tell you they love you? Why or why not?",
    "What have you gained from pursuing something you knew you were terrible at?",
    "Are you too hard on yourself?",
    "Are you a patient person?",
    "How impulsive are you?",
    "What annoys you?",
    "Are there any hobbies you used to love but for one reason or another, you don't do anymore?",
    "What's one small thing that made you happy today?",
    "Have you ever felt pressured by people around you to make an important decision about your life? What happened?",
    "What's the story behind your name?",
    "What family traditions do you personally want to continue?",
    "What advice would you give to a parent of a teenager?",
    "What urban legends are there about the place(s) you grew up?",
    "What's the first material thing you would grab in the event of a fire?",
    "What city do you think you'd feel the most at home at?",
    "Can you keep a secret?",
    "Could you live a year without internet?",
    "Name a character from a tv show/movie/game/etc that you can't stand and why.",
    "Are you friends with anyone you never expected to be friends with? How did you get close?",
    "What hurts more, ending a romantic relationship or a friendship?",
    "If someone proposed to you in public, how would you react?",
    "Is cheating on a partner ever okay?",
    "Is there a meaning behind your social media handle(s)?",
    "Is there a person you have complicated emotions towards? What happened?",
    "In your opinion, what does a relationship need to work out?",
    "What is the best decision you've made in your life so far?",
    "What do you really need right now?",
    "Have you ever been in an ambulance?",
    "Are you a hard person to live with?",
    "What is one thing you really need to get rid of?",
    "The last time you felt this way, what did you do?",
    "What is your inner critic saying to you lately?",
    "What do you need to accept right now?",
    "How much have you changed in the past 5 years?",
    "What do you wish to let go of?",
    "How could someone best support you when you're down?",
    "Who makes you feel appreciated?",
    "Has anyone ever been afraid of you? Do you have any idea why?",
    "If you could meet your younger self, what do you think they'd feel most proud of you for achieving?",
    "What drained your energy last week?",
    "How do you usually get yourself out of a rut?",
    "Do you have a favorite commercial? Why do you like it so much?",
    "What is something you're passionate about, and why does it matter to you?",
    "Describe a recent challenge you faced and what you learned from it.",
    "What role does self-compassion play in your life, and how can you cultivate more of it?",
    "Explore your relationship with time. Do you often feel rushed or present in the moment?",
    "Are there any patterns in the people you are drawn to?",
    "What are some of the ways you put yourself first?",
    "Have you ever had an encounter with a stranger that wound up changing your life?",
    "What's pissing you off right now?",
    "What are the parts of yourself that you absolutely love?",
    "If you met your younger self, what would they be most disappointed to know about present you?",
    "What do you need more of this month?",
    "What are 5 things you would tell yourself 5 years ago?",
    "Have you been taking care of yourself lately?",
    "How do you stay calm during moments of chaos?",
    "Do you believe everything is fated by destiny or that everyone has free will?",
    "Write about a time you told a lie for a good reason. Was it the right choice?",
    "Does your life now look like you imagined it would when you were a kid?",
    "In general, do you see yourself as a happy person?",
    "Do you always feel supported by the people around you?",
    "Do you feel older or younger than your actual age?",
    "What do you hope to have achieved by your next birthday?",
    "If you knew you would die tomorrow, what would change about the way you'd live today?",
    "Do you think it's better to pursue your passions or something that already aligns with your skills?",
    "What was the most challenging relationship you've ever had and what made things so difficult?",
    "Which fast food restaurant is your favorite and why do you prefer it over the others?",
    "What virtue do you wish you had more of and why?",
    "Is it ever ethical to break the law?",
    "How do you handle rejection?",
    "What is your typical reaction when you don't get your way?",
    "What's a random fact about you that always surprises people when they find out about it?",
    "The world is about to end. What should be the last song ever played?",
    "What's something someone has said to or about you that's stuck with you ever since?",
    "What's something you feel judged for?",
    "What is the lie you tell yourself most often?",
    "What is your worst habit, and what is keeping you from dropping it?",
    "Is humanity inherently good or evil?",
    "Would you rather spend time floating alone in space, or floating alone at sea?",
    "What do you know about your neighbors that they don't know that you know? What do you think they know about you that you don't know that they know?",
    "Listen to yourself think. What does your mind voice sound like? Do you think your mind voice is inherent to your mind, or do you think you developed your mind voice based on hearing your speaking voice?",
    "What are some of the ways you neglect yourself?",
    "What is making life hard right now?",
    "Do you miss any of your ex friends? If you could say one thing to them, what would you say?",
    "What's the worst fight you've ever had? What happened afterwards?",
    "What's the weirdest food combination you've ever tried and enjoyed?",
    "What's something personal you'd be comfortable sharing with a stranger?",
    "What new boundaries would you like to set for future relationships?",
    "What is your healthiest habit?",
    "If you switched bodies with your favorite celebrity, would you actually be able to convince others that you're them?",
    "If you had to share your writings with anyone else, who would you choose and why?",
    "What was the last gift you gifted yourself?",
  ];

  // new prompt button
  
  function newPrompt() {
    let randomNumber = Math.floor(Math.random() * (prompts.length));
    document.getElementById('journalPrompt').innerHTML = prompts[randomNumber];
  }

  // display only month and day
let date = new Date();
let months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
let days = ['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th', '11th', '12th', '13th', '14th', '15th', '16th', '17th', '18th', '19th', '20th', '21th', '22nd', '23rd', '24th', '25th', '26th', '27th', '28th', '29th', '30th', '31st'];

function formatDay(date){
    let month = date.getMonth();
    let monthName = months[month];
    let day = date.getDate() - 1;
    let dayNum = days[day];

    return `${monthName} ${dayNum}`;
}

// display only hours:minutes
function formatTime(date){
    let hours = date.getHours();
    let minutes = date.getMinutes();
    let dayOrNight = hours > 12 ? "pm" : "am";
    hours = (hours % 12) || 12;

    minutes = addZero(minutes);

    return `${hours}:${minutes} ${dayOrNight}`;
}
// add zeroes
function addZero(time){
    time = time.toString();
    return time.length < 2 ? "0" + time : time;
}

document.getElementById('dateTxt').innerHTML = formatDay(date);
document.getElementById('timeTxt').innerHTML = formatTime(date);